### ISSUE TITLE
FFprobe is x86_64 only

### ISSUE THREAD

**Issue by section83** [eakriulin/ffprobe-static-arm64#1]
Hello,

I'm keen to find an ARM64 version of FFprobe.  Your repo looked promising and I downloaded the FFprobe binary from here: https://github.com/eakriulin/ffprobe-static-arm64/blob/main/bin/darwin/arm64/ffprobe.

After downloading, I did a "chmod a+x ffprobe" then, "lipo ffprobe -archs".  Lipo reported that the file was x86_64.

Do you plan to release an ARM64 version of FFprobe ?

**Comment by eakriulin** [comment]
Hello @section83,

Thank you for opening this issue. I am not the original author of ffprobe — [here is the one you need](https://github.com/joshwnj/ffprobe-static). The only purpose of my repository was to add one small "hack" and use the same binary for both `x64` and `arm64` architectures. 

I realised that `arm64` wasn't supported by the original library when I migrated to a MacBook Pro with the M1 processor. I played with the binaries and found out that `x64` one works fine with the `arm64` architecture. It's reasonable because Apple announced back then that the 64-bit apps should work on the new generation of their laptops. So, I started using this binary for my local development purposes and created this repository to make the life of other team members easier.

In the original project, there is an opened issue and a relevant pull request to support `arm64`. Hopefully, the author will be able to respond soon!

**Comment by section83** [comment]
Thank you for the response.  I believe x86_64 executables do work on M1 Macs because Apple have implemented Rosetta 2 in macOS.  There is only a small amount of speed lost in the translation, evidence of how well Rosetta 2 works.

I have users who wish to work with ARM64 executables only so, I have found a source of ARM64-macOS binaries.

>In the original project, there is an opened issue and a relevant pull request to support arm64.

I didn't know that, thanks.
